### ISSUE TITLE
Test python_fv3 graphic package

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ShunLiu-NOAA/regional_workflow#42]

**Comment by ShunLiu-NOAA** [comment]
test launch_INCREMENTS:
1. change the path to Shun's directory
2. source ~/u/Shun.Liu/bin/loadp.sh

**Comment by ShunLiu-NOAA** [comment]
Traceback (most recent call last):
  File "/gpfs/dell2/emc/modeling/noscrub/Shun.Liu/python.fv3/compare_nam/plot_fv3_ptype_dif.py", line 253, in <module>
    paraind=pygrib.index('/gpfs/dell4/ptmp/emc.campara/fv3lam/fv3lam.'+str(ymd)+'/'+cyc+'/fv3lam.t'+cyc+'z.conus.f'+fhr+'.grib2','name','level')
  File "pygrib.pyx", line 1904, in pygrib.index.__cinit__
RuntimeError: b'Wrong message length'
+ wait
+ exit
